name: binny_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  #Widget
  carousel_slider: ^4.2.1
  sliding_up_panel: ^2.0.0+1

  #Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0

  flutter:
    sdk: flutter

  #Font
  google_fonts: ^6.2.1

  #Firebase
  firebase_core: ^2.30.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/donationpage/
    - assets/garden/
    - assets/homepage/
    - assets/trash/
    - assets/katoo/
    - assets/profile/
    - assets/icons/
    - assets/images/
    - assets/images/rewards/
